Serge server
sergeychur/TP_CPP_PROJECT pull request #4
Opened 2018-12-03 21:56 UTC by sergeychur

Открываю pull request, возникшие замечания(по поводу handlerов в обработке команд) исправлю чуть позднее

2018-12-17 13:32 UTC, sergeychur commented
Готов к ревью

2018-12-18 21:07 UTC, sergeychur commented
CI вроде работает, прикрепляю скрин
![2018-12-19 00-02-21](https://user-images.githubusercontent.com/33199039/50183008-f6be9500-0321-11e9-8a16-8fd9d8884328.png)

2018-12-23 19:58 UTC, leshiy1295 requested changes
очень добротный код!
но с Boost всё же не до конца везде есть развязка (по крайней мере на момент дедлайна)

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/CMakeLists.txt
> +set(PROJECT_ROOT ../../)
кажется, что это не очень хорошо

2018-12-23 19:58 UTC, leshiy1295 commented on linters/run.sh
> +#${CPPCHECK} server_without_send --enable=all --error-exitcode=1 -I server_without_send/include --suppress=missingIncludeSystem --inline-suppr # --check-config
а почему закомментировано?

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/game/include/adapter.hpp
> +					 std::map<std::string, DefaultAbstractFactory *> _map) :
лучше не передавать map, а сделать отдельный класс для этого
map - это про хранение, а не про семантику

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/game/include/base.hpp
> +	bool is_alive() override { return HP > 0; }
по styleguide в C++ всё же названия методов - с большой буквы и через CamelCase

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/game/include/game.hpp
> + private:
сначала стоит размещать public, потом - private

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/game/include/input.hpp
> +		std::cout << greeting << std::endl;
завязались тут на cout/cin
стоило передавать их тоже в качестве параметров
как минимум, через интерфейс istream и ostream, но можно было бы использовать и шаблоны

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/game/include/mediator.hpp
> +	virtual void delete_colleague(size_t player_id, size_t unit_id) = 0;
size_t стоит использовать только там, где есть size =)
в остальных случаях лучше использовать обычный int

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/game/include/unit.hpp
> +class Unit : public AbstractUnit, public RealUnit {
кажется, что такой код уже был выше

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/game/src/base.cpp
> +Base::Base(std::shared_ptr<Mediator> med, const int HP, const int _x,
Base - не самое удачное название класса

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/game/src/unit.cpp
> +																						  RealUnit(_player_id,
что-то пошло не так с отступами

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/game/src/unit.cpp
> +	while (it != act_handlers.end()) {
можно было бы тоже вынести в отдельный слой - регистрацию обработчиков + обход по ним, чтобы не дублировать в разных классах

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/main.cpp
> +	size_t player_num = 0;
main оказался перегруженным...

2018-12-23 19:58 UTC, leshiy1295 commented on server_side/server/xml_make/xml.cpp
> +	BOOST_FOREACH(const auto &elem, bases) {
хардкодить BOOST в main - тоже не очень классная идея...

2018-12-23 19:58 UTC, leshiy1295 commented on shared_files/include/command.hpp
> +#include "Serializable.h"
класс оказался сильно связанным на boost :(

2018-12-23 19:58 UTC, leshiy1295 commented on shared_files/include/update.hpp
> +#include <boost/serialization/string.hpp>
и этот

2018-12-23 19:58 UTC, leshiy1295 commented on shared_files/src/command.cpp
> +			{"check",       4},
магические константы

2019-03-14 15:20 UTC, merged